// <auto-generated />
namespace WebAppJobInterview.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class remove_migration_test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_migration_test));
        
        string IMigrationMetadata.Id
        {
            get { return "201709300844240_remove_migration_test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
